"""Code annotation parsing and `_code-index.md` emission for the Assured bundle.

This module provides two public functions:

- ``parse_code_annotations`` — scans a list of source files for
  ``# implements:`` annotations and returns a structured list of
  :class:`CodeIndexEntry` records.
- ``render_code_index`` — serialises a list of entries to a
  shelf-index-shaped Markdown string suitable for ingestion by the
  sdlc-knowledge-base librarian.

The shelf-index format mirrors the format used by the knowledge-base
library (``format_version``, ``last_rebuilt``, ``library_handle``
header comments) so that the emitted file can be treated as a first-
class library document without further post-processing.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional


from .ids import IdRecord

_IMPLEMENTS_RE = re.compile(r"^\s*#\s*implements:\s*(?P<ids>.+)$")
_ID_TOKEN_RE = re.compile(
    r"\b((?:P\d+\.SP\d+\.M\d+\.)?(?:REQ|DES|TEST|CODE)-(?:[a-z0-9][a-z0-9-]*-)?\d+)\b"
)


@dataclass(frozen=True)
class CodeIndexEntry:
    """A single ``# implements:`` annotation extracted from a source file."""

    file_path: str
    line: int
    cited_ids: List[str]
    terms: List[str] = field(default_factory=list)
    facts: List[str] = field(default_factory=list)


def parse_code_annotations(
    files: List[Path], project_root: Path
) -> List[CodeIndexEntry]:
    """Walk *files* and extract every ``# implements:`` annotation.

    Parameters
    ----------
    files:
        Explicit list of :class:`~pathlib.Path` objects to inspect.
    project_root:
        Used to relativise file paths in the returned entries.

    Returns
    -------
    List[CodeIndexEntry]
        One entry per annotation line found, in file-then-line order.
    """
    entries: List[CodeIndexEntry] = []
    for f in files:
        if not f.is_file():
            continue
        text = f.read_text(encoding="utf-8")
        if f.parent == project_root or project_root in f.parents:
            rel_path = str(f.relative_to(project_root))
        else:
            rel_path = str(f.name)
        for line_no, line in enumerate(text.splitlines(), start=1):
            m = _IMPLEMENTS_RE.match(line)
            if not m:
                continue
            cited = _ID_TOKEN_RE.findall(m["ids"])
            entries.append(
                CodeIndexEntry(
                    file_path=rel_path,
                    line=line_no,
                    cited_ids=cited,
                )
            )
    return entries


def render_code_index(entries: List[CodeIndexEntry], library_handle: str) -> str:
    """Serialise *entries* to a shelf-index-shaped Markdown string.

    The output begins with the four standard shelf-index header comments
    (``format_version``, ``last_rebuilt``, ``library_handle``,
    ``library_description``) followed by numbered section entries in the
    format consumed by the sdlc-knowledge-base librarian.

    Parameters
    ----------
    entries:
        Ordered list of :class:`CodeIndexEntry` objects to render.
    library_handle:
        The ``library_handle`` value to embed in the header comment.

    Returns
    -------
    str
        The complete shelf-index Markdown document as a single string.
    """
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        "<!-- format_version: 1 -->",
        f"<!-- last_rebuilt: {timestamp} -->",
        f"<!-- library_handle: {library_handle} -->",
        "<!-- library_description: Code index — annotation-derived shelf-index for source code -->",
        "# Code Index",
        "",
        "Generated by `kb-codeindex`. Each entry corresponds to one `# implements:` annotation in source code.",
        "",
        "---",
        "",
    ]
    for n, e in enumerate(entries, start=1):
        terms = ", ".join(e.terms) if e.terms else ""
        lines.append(f"## {n}. {e.file_path}:{e.line}")
        lines.append("")
        lines.append(f"**Terms:** {terms}")
        if e.facts:
            lines.append("**Facts:**")
            for fact in e.facts:
                lines.append(f"- {fact}")
        else:
            lines.append("**Facts:**")
        lines.append(f"**Links:** {', '.join(e.cited_ids)}")
        lines.append("")
    return "\n".join(lines)


def render_spec_findings(records: List[IdRecord], library_handle: str) -> str:
    """Render REQ/DES/TEST records as shelf-index entries (spec-as-KB-finding)."""
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        "<!-- format_version: 1 -->",
        f"<!-- last_rebuilt: {timestamp} -->",
        f"<!-- library_handle: {library_handle} -->",
        "<!-- library_description: Spec findings — REQ/DES/TEST records as shelf-index entries -->",
        "# Spec Findings",
        "",
    ]
    for n, r in enumerate(records, start=1):
        feature = _feature_from_id(r.id)
        terms = ", ".join([r.kind] + ([feature] if feature else []))
        links = ", ".join(r.satisfies) if r.satisfies else r.source
        lines.append(f"## {n}. {r.id}")
        lines.append("")
        lines.append(f"**Terms:** {terms}")
        lines.append("**Facts:**")
        lines.append(f"- Declared in {r.source}")
        lines.append(f"**Links:** {links}")
        lines.append("")
    return "\n".join(lines)


def _feature_from_id(id_: str) -> Optional[str]:
    """Extract the feature segment from a flat ID such as ``REQ-auth-001``.

    Parameters
    ----------
    id_:
        A string ID, either flat (``REQ-feature-NNN``) or positional
        (``P1.SP1.M1.REQ-NNN``).

    Returns
    -------
    Optional[str]
        The feature name for flat IDs, or ``None`` for positional IDs and IDs
        that do not contain a feature segment.
    """
    if id_.startswith("P") and "." in id_:
        return None
    parts = id_.split("-")
    if len(parts) >= 3:
        return parts[1]
    return None
