"""Code annotation parsing and `_code-index.md` emission for the Assured bundle.

This module provides two public functions:

- ``parse_code_annotations`` — scans a list of source files for
  ``# implements:`` annotations and returns a structured list of
  :class:`CodeIndexEntry` records.
- ``render_code_index`` — serialises a list of entries to a
  shelf-index-shaped Markdown string suitable for ingestion by the
  sdlc-knowledge-base librarian.

The shelf-index format mirrors the format used by the knowledge-base
library (``format_version``, ``last_rebuilt``, ``library_handle``
header comments) so that the emitted file can be treated as a first-
class library document without further post-processing.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, List, Mapping, Optional

if TYPE_CHECKING:
    from .requirement_metadata import RequirementMetadata

from .ids import IdRecord

_IMPLEMENTS_RE = re.compile(r"^\s*#\s*implements:\s*(?P<ids>.+)$")
_ID_TOKEN_RE = re.compile(
    r"\b((?:P\d+\.SP\d+\.M\d+\.)?(?:REQ|DES|TEST|CODE)-(?:[a-z0-9][a-z0-9-]*-)?\d+)\b"
)


@dataclass(frozen=True)
class CodeIndexEntry:
    """A single ``# implements:`` annotation extracted from a source file."""

    file_path: str
    line: int
    cited_ids: List[str]
    terms: List[str] = field(default_factory=list)
    facts: List[str] = field(default_factory=list)


def parse_code_annotations(
    files: List[Path], project_root: Path
) -> List[CodeIndexEntry]:
    """Walk files via EvidenceIndexRegistry; convert PYTHON_COMMENT entries to CodeIndexEntry.

    v0.1.0 compatibility shim: returns CodeIndexEntry for backward compatibility with
    existing render_code_index calls. New code paths should use EvidenceIndexRegistry directly.
    """
    from .evidence_index import EvidenceIndexRegistry, EvidenceKind

    registry = EvidenceIndexRegistry.with_default_adapters()
    entries: List[CodeIndexEntry] = []
    for ev in registry.scan(files, project_root):
        if ev.kind != EvidenceKind.PYTHON_COMMENT:
            continue
        entries.append(
            CodeIndexEntry(
                file_path=ev.source,
                line=ev.line or 0,
                cited_ids=list(ev.cited_ids),
            )
        )
    return entries


def render_code_index(
    entries: List[CodeIndexEntry],
    library_handle: str,
    timestamp: Optional[str] = None,
) -> str:
    # implements: DES-assured-code-index-002
    """Serialise *entries* to a shelf-index-shaped Markdown string.

    The output begins with the standard shelf-index header comments
    (``format_version``, optionally ``last_rebuilt``, ``library_handle``,
    ``library_description``) followed by numbered section entries in the
    format consumed by the sdlc-knowledge-base librarian.

    Parameters
    ----------
    entries:
        Ordered list of :class:`CodeIndexEntry` objects to render.
    library_handle:
        The ``library_handle`` value to embed in the header comment.
    timestamp:
        Optional ISO 8601 string for the ``last_rebuilt`` header field.
        When ``None`` (the default) the ``last_rebuilt`` line is omitted so
        that repeated calls on unchanged inputs produce byte-identical output.
        Pass an explicit value when a stable rebuild timestamp is required
        (e.g. ``kb-rebuild-indexes`` managing the library record).

    Returns
    -------
    str
        The complete shelf-index Markdown document as a single string.
    """
    lines = [
        "<!-- format_version: 1 -->",
    ]
    if timestamp is not None:
        lines.append(f"<!-- last_rebuilt: {timestamp} -->")
    lines += [
        f"<!-- library_handle: {library_handle} -->",
        "<!-- library_description: Code index — annotation-derived shelf-index for source code -->",
        "# Code Index",
        "",
        "Generated by `kb-codeindex`. Each entry corresponds to one `# implements:` annotation in source code.",
        "",
        "---",
        "",
    ]
    for n, e in enumerate(entries, start=1):
        terms = ", ".join(e.terms) if e.terms else ""
        lines.append(f"## {n}. {e.file_path}:{e.line}")
        lines.append("")
        lines.append(f"**Terms:** {terms}")
        if e.facts:
            lines.append("**Facts:**")
            for fact in e.facts:
                lines.append(f"- {fact}")
        else:
            lines.append("**Facts:**")
        lines.append(f"**Links:** {', '.join(e.cited_ids)}")
        lines.append("")
    return "\n".join(lines)


def render_spec_findings(
    records: List[IdRecord],
    library_handle: str,
    timestamp: Optional[str] = None,
    metadata: Optional[Mapping[str, "RequirementMetadata"]] = None,
) -> str:
    # implements: DES-assured-code-index-002
    """Render REQ/DES/TEST records as shelf-index entries (spec-as-KB-finding).

    Parameters
    ----------
    records:
        Ordered list of :class:`~assured.ids.IdRecord` objects to render.
    library_handle:
        The ``library_handle`` value to embed in the header comment.
    timestamp:
        Optional ISO 8601 string for the ``last_rebuilt`` header field.
        When ``None`` (the default) the ``last_rebuilt`` line is omitted so
        that repeated calls on unchanged inputs produce byte-identical output.
    metadata:
        Optional mapping from requirement ID to :class:`RequirementMetadata`.
        When provided and an entry has a non-empty ``related`` list, a
        ``**Related:**`` line is appended to that entry's rendered block.
        Entries without metadata or with an empty ``related`` list emit no
        ``Related:`` line.
    """
    lines = [
        "<!-- format_version: 1 -->",
    ]
    if timestamp is not None:
        lines.append(f"<!-- last_rebuilt: {timestamp} -->")
    lines += [
        f"<!-- library_handle: {library_handle} -->",
        "<!-- library_description: Spec findings — REQ/DES/TEST records as shelf-index entries -->",
        "# Spec Findings",
        "",
    ]
    for n, r in enumerate(records, start=1):
        feature = _feature_from_id(r.id)
        terms = ", ".join([r.kind] + ([feature] if feature else []))
        links = ", ".join(r.satisfies) if r.satisfies else r.source
        lines.append(f"## {n}. {r.id}")
        lines.append("")
        lines.append(f"**Terms:** {terms}")
        lines.append("**Facts:**")
        lines.append(f"- Declared in {r.source}")
        lines.append(f"**Links:** {links}")
        md = metadata.get(r.id) if metadata else None
        if md is not None and md.related:
            lines.append(f"**Related:** {', '.join(md.related)}")
        lines.append("")
    return "\n".join(lines)


def _feature_from_id(id_: str) -> Optional[str]:
    """Extract the feature segment from a flat ID such as ``REQ-auth-001``.

    Parameters
    ----------
    id_:
        A string ID, either flat (``REQ-feature-NNN``) or positional
        (``P1.SP1.M1.REQ-NNN``).

    Returns
    -------
    Optional[str]
        The feature name for flat IDs, or ``None`` for positional IDs and IDs
        that do not contain a feature segment.
    """
    if id_.startswith("P") and "." in id_:
        return None
    parts = id_.split("-")
    if len(parts) >= 3:
        return parts[1]
    return None
