"""Standard-specific traceability exports."""

from __future__ import annotations

from collections import defaultdict
from typing import List

from .code_index import CodeIndexEntry
from .evidence_status import EvidenceStatus
from .ids import IdRecord


def _index_by_satisfies(records: List[IdRecord]) -> dict[str, list[IdRecord]]:
    """Records keyed by what they satisfy: target_id → [records that cite target_id]."""
    out: dict[str, list[IdRecord]] = defaultdict(list)
    for r in records:
        for target in r.satisfies:
            out[target].append(r)
    return out


def _code_by_cited(code: List[CodeIndexEntry]) -> dict[str, list[CodeIndexEntry]]:
    """Code entries keyed by cited ID: cited_id → [entries that cite that ID]."""
    out: dict[str, list[CodeIndexEntry]] = defaultdict(list)
    for c in code:
        for cited in c.cited_ids:
            out[cited].append(c)
    return out


def export_do178c_rtm(records: List[IdRecord], code: List[CodeIndexEntry]) -> str:
    """DO-178C Requirements Traceability Matrix.

    Columns: HLR (high-level requirement) | LLR (low-level requirement / design) |
    Source code | Test case.

    **DES:** DES-assured-export-formats-001
    """
    cited_by = _index_by_satisfies(records)
    code_by_cited = _code_by_cited(code)
    lines = [
        "# Requirements Traceability Matrix (DO-178C)",
        "",
        (
            "Generated by `traceability-export do-178c-rtm`. Each row links a high-level requirement "
            + "to its low-level requirements (designs), implementing source code, and verifying test cases."
        ),
        "",
        "| HLR | LLR | Source code | Test case |",
        "|-----|-----|-------------|-----------|",
    ]
    _missing = EvidenceStatus.MISSING.display()
    reqs = [r for r in records if r.kind == "REQ"]
    for req in reqs:
        deses = [d for d in cited_by.get(req.id, []) if d.kind == "DES"]
        for des in deses:
            tests = [t for t in cited_by.get(des.id, []) if t.kind == "TEST"]
            code_locs = code_by_cited.get(req.id, []) + code_by_cited.get(des.id, [])
            code_str = (
                ", ".join(f"{c.file_path}:{c.line}" for c in code_locs) or _missing
            )
            test_str = ", ".join(t.id for t in tests) or _missing
            lines.append(f"| {req.id} | {des.id} | {code_str} | {test_str} |")
        if not deses:
            lines.append(f"| {req.id} | {_missing} | {_missing} | {_missing} |")
    return "\n".join(lines) + "\n"


def export_iec_62304_matrix(
    records: List[IdRecord],
    code: List[CodeIndexEntry],
    software_safety_class: str = "A",
) -> str:
    """IEC 62304 Software Traceability Matrix.

    Columns: Software requirement | Software unit (code) | Verification activity (test).
    Software safety class is declared in the heading (A, B, or C).

    **DES:** DES-assured-export-formats-002
    """
    cited_by = _index_by_satisfies(records)
    code_by_cited = _code_by_cited(code)
    lines = [
        "# IEC 62304 Software Traceability Matrix",
        "",
        f"Software safety class: {software_safety_class}",
        "",
        "| Software requirement | Software unit | Verification activity |",
        "|----------------------|---------------|------------------------|",
    ]
    _missing = EvidenceStatus.MISSING.display()
    reqs = [r for r in records if r.kind == "REQ"]
    for req in reqs:
        units = code_by_cited.get(req.id, [])
        deses = [d for d in cited_by.get(req.id, []) if d.kind == "DES"]
        tests: List[IdRecord] = []
        for des in deses:
            units.extend(code_by_cited.get(des.id, []))
            tests.extend([t for t in cited_by.get(des.id, []) if t.kind == "TEST"])
        unit_str = ", ".join(f"{c.file_path}:{c.line}" for c in units) or _missing
        test_str = ", ".join(t.id for t in tests) or _missing
        lines.append(f"| {req.id} | {unit_str} | {test_str} |")
    return "\n".join(lines) + "\n"


def export_iso_26262_asil_matrix(
    records: List[IdRecord], code: List[CodeIndexEntry], asil_level: str = "B"
) -> str:
    """ISO 26262 ASIL Traceability Matrix.

    Columns: Safety requirement | Architectural element (design) |
    Implementation (code) | Verification (test).

    **DES:** DES-assured-export-formats-003
    """
    cited_by = _index_by_satisfies(records)
    code_by_cited = _code_by_cited(code)
    lines = [
        "# ISO 26262 ASIL Traceability Matrix",
        "",
        f"ASIL: {asil_level}",
        "",
        "| Safety requirement | Architectural element | Implementation | Verification |",
        "|---------------------|----------------------|----------------|---------------|",
    ]
    _missing = EvidenceStatus.MISSING.display()
    reqs = [r for r in records if r.kind == "REQ"]
    for req in reqs:
        deses = [d for d in cited_by.get(req.id, []) if d.kind == "DES"]
        for des in deses:
            tests = [t for t in cited_by.get(des.id, []) if t.kind == "TEST"]
            code_locs = code_by_cited.get(req.id, []) + code_by_cited.get(des.id, [])
            code_str = (
                ", ".join(f"{c.file_path}:{c.line}" for c in code_locs) or _missing
            )
            test_str = ", ".join(t.id for t in tests) or _missing
            lines.append(f"| {req.id} | {des.id} | {code_str} | {test_str} |")
        if not deses:
            lines.append(f"| {req.id} | {_missing} | {_missing} | {_missing} |")
    return "\n".join(lines) + "\n"


def export_fda_dhf_structure(
    records: List[IdRecord], code: List[CodeIndexEntry]
) -> str:
    """FDA Design History File structure (21 CFR §820.30).

    Sections: Design inputs (REQs) | Design outputs (DESs + code) |
    Design verification (TESTs) | Design validation (placeholder for human attestation).

    **DES:** DES-assured-export-formats-004
    """
    _missing = EvidenceStatus.MISSING.display()
    reqs = [r for r in records if r.kind == "REQ"]
    deses = [r for r in records if r.kind == "DES"]
    tests = [r for r in records if r.kind == "TEST"]
    lines = [
        "# FDA Design History File (21 CFR §820.30)",
        "",
        (
            "Generated by `traceability-export fda-dhf-structure`. This document organises"
            + " traceability artefacts under the design control sections of 21 CFR §820.30."
        ),
        "",
        "## Design inputs",
        "",
        "(Per §820.30(c) — Design inputs)",
        "",
    ]
    for r in reqs:
        lines.append(f"- **{r.id}**: see {r.source}")
    if not reqs:
        lines.append("_(no requirements declared)_")
    lines.extend(["", "## Design outputs", "", "(Per §820.30(d) — Design outputs)", ""])
    for d in deses:
        lines.append(f"- **{d.id}** satisfies {', '.join(d.satisfies)}: see {d.source}")
    lines.append("")
    for c in code:
        lines.append(
            f"- Source code: `{c.file_path}:{c.line}` implements {', '.join(c.cited_ids)}"
        )
    if not deses and not code:
        lines.append(f"_({_missing} — no design outputs declared)_")
    lines.extend(
        ["", "## Design verification", "", "(Per §820.30(f) — Design verification)", ""]
    )
    for t in tests:
        lines.append(f"- **{t.id}** verifies {', '.join(t.satisfies)}: see {t.source}")
    if not tests:
        lines.append(f"_({_missing} — no verification tests declared)_")
    lines.extend(
        [
            "",
            "## Design validation",
            "",
            "(Per §820.30(g) — Design validation)",
            "",
            (
                "_Design validation is performed under defined operating conditions on initial"
                + " production units, units that simulate them, or their equivalents._"
                + " This section is a placeholder for human-attested validation evidence;"
                + " the framework does not auto-populate it."
            ),
            "",
        ]
    )
    return "\n".join(lines)


def _build_rows(
    records: List[IdRecord], code: List[CodeIndexEntry]
) -> list[tuple[str, str, str, str]]:
    """Shared helper — yields one row per (REQ, DES, tests, code) combination.

    Emits a stub row for any REQ with no DES.
    """
    cited_by = _index_by_satisfies(records)
    code_by_cited = _code_by_cited(code)
    rows: list[tuple[str, str, str, str]] = []
    for req in [r for r in records if r.kind == "REQ"]:
        deses = [d for d in cited_by.get(req.id, []) if d.kind == "DES"]
        if not deses:
            rows.append((req.id, "", "", ""))
            continue
        for des in deses:
            tests = [t for t in cited_by.get(des.id, []) if t.kind == "TEST"]
            code_locs = code_by_cited.get(req.id, []) + code_by_cited.get(des.id, [])
            code_str = "; ".join(f"{c.file_path}:{c.line}" for c in code_locs)
            test_str = "; ".join(t.id for t in tests)
            rows.append((req.id, des.id, test_str, code_str))
    return rows


def export_csv(records: List[IdRecord], code: List[CodeIndexEntry]) -> str:
    """Generic CSV traceability export.

    Header: REQ,DES,TEST,CODE. Commas within cells are replaced with semicolons
    to avoid breaking the CSV structure.

    **DES:** DES-assured-export-formats-004 (non-regulatory companion)
    """
    rows = _build_rows(records, code)
    out = ["REQ,DES,TEST,CODE"]
    for r in rows:
        out.append(",".join(c.replace(",", ";") for c in r))
    return "\n".join(out) + "\n"


def export_markdown(records: List[IdRecord], code: List[CodeIndexEntry]) -> str:
    """Generic Markdown traceability matrix export.

    Produces a ``# Traceability Matrix`` title followed by a GFM pipe table
    with columns: REQ | DES | TEST | CODE.

    **DES:** DES-assured-export-formats-004 (non-regulatory companion)
    """
    rows = _build_rows(records, code)
    out = [
        "# Traceability Matrix",
        "",
        "| REQ | DES | TEST | CODE |",
        "|-----|-----|------|------|",
    ]
    for r in rows:
        out.append("| " + " | ".join(r) + " |")
    return "\n".join(out) + "\n"
