"""Standard-specific traceability exports."""

from __future__ import annotations

from collections import defaultdict
from typing import List

from .code_index import CodeIndexEntry
from .ids import IdRecord


def _index_by_satisfies(records: List[IdRecord]) -> dict[str, list[IdRecord]]:
    """Records keyed by what they satisfy: target_id → [records that cite target_id]."""
    out: dict[str, list[IdRecord]] = defaultdict(list)
    for r in records:
        for target in r.satisfies:
            out[target].append(r)
    return out


def _code_by_cited(code: List[CodeIndexEntry]) -> dict[str, list[CodeIndexEntry]]:
    """Code entries keyed by cited ID: cited_id → [entries that cite that ID]."""
    out: dict[str, list[CodeIndexEntry]] = defaultdict(list)
    for c in code:
        for cited in c.cited_ids:
            out[cited].append(c)
    return out


def export_do178c_rtm(records: List[IdRecord], code: List[CodeIndexEntry]) -> str:
    """DO-178C Requirements Traceability Matrix.

    Columns: HLR (high-level requirement) | LLR (low-level requirement / design) |
    Source code | Test case.
    """
    cited_by = _index_by_satisfies(records)
    code_by_cited = _code_by_cited(code)
    lines = [
        "# Requirements Traceability Matrix (DO-178C)",
        "",
        "Generated by `traceability-export do-178c-rtm`. Each row links a high-level requirement "
        "to its low-level requirements (designs), implementing source code, and verifying test cases.",
        "",
        "| HLR | LLR | Source code | Test case |",
        "|-----|-----|-------------|-----------|",
    ]
    reqs = [r for r in records if r.kind == "REQ"]
    for req in reqs:
        deses = [d for d in cited_by.get(req.id, []) if d.kind == "DES"]
        for des in deses:
            tests = [t for t in cited_by.get(des.id, []) if t.kind == "TEST"]
            code_locs = code_by_cited.get(req.id, []) + code_by_cited.get(des.id, [])
            code_str = ", ".join(f"{c.file_path}:{c.line}" for c in code_locs) or "—"
            test_str = ", ".join(t.id for t in tests) or "—"
            lines.append(f"| {req.id} | {des.id} | {code_str} | {test_str} |")
        if not deses:
            lines.append(f"| {req.id} | — | — | — |")
    return "\n".join(lines) + "\n"


def export_iec_62304_matrix(
    records: List[IdRecord],
    code: List[CodeIndexEntry],
    software_safety_class: str = "A",
) -> str:
    """IEC 62304 Software Traceability Matrix.

    Columns: Software requirement | Software unit (code) | Verification activity (test).
    Software safety class is declared in the heading (A, B, or C).
    """
    cited_by = _index_by_satisfies(records)
    code_by_cited = _code_by_cited(code)
    lines = [
        "# IEC 62304 Software Traceability Matrix",
        "",
        f"Software safety class: {software_safety_class}",
        "",
        "| Software requirement | Software unit | Verification activity |",
        "|----------------------|---------------|------------------------|",
    ]
    reqs = [r for r in records if r.kind == "REQ"]
    for req in reqs:
        units = code_by_cited.get(req.id, [])
        deses = [d for d in cited_by.get(req.id, []) if d.kind == "DES"]
        tests: List[IdRecord] = []
        for des in deses:
            units.extend(code_by_cited.get(des.id, []))
            tests.extend([t for t in cited_by.get(des.id, []) if t.kind == "TEST"])
        unit_str = ", ".join(f"{c.file_path}:{c.line}" for c in units) or "—"
        test_str = ", ".join(t.id for t in tests) or "—"
        lines.append(f"| {req.id} | {unit_str} | {test_str} |")
    return "\n".join(lines) + "\n"
