"""Positional namespace ID parsing for the Assured bundle."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional


class IdParseError(ValueError):
    """Raised when a string cannot be parsed as an Assured ID."""


@dataclass(frozen=True)
class ParsedId:
    """Decomposed view of an Assured ID."""

    program: Optional[str]
    sub_program: Optional[str]
    module: Optional[str]
    kind: str
    feature: Optional[str]
    number: int


_FLAT_RE = re.compile(
    r"^(?P<kind>REQ|DES|TEST|CODE)-(?P<feature>[a-z0-9][a-z0-9-]*)-(?P<num>\d+)$"
)
_POSITIONAL_RE = re.compile(
    r"^(?P<prog>P\d+)\.(?P<sub>SP\d+)\.(?P<mod>M\d+)\."
    r"(?P<kind>REQ|DES|TEST|CODE)-(?P<num>\d+)$"
)


def parse_id(text: str) -> ParsedId:
    flat = _FLAT_RE.match(text)
    if flat:
        return ParsedId(
            program=None,
            sub_program=None,
            module=None,
            kind=flat["kind"],
            feature=flat["feature"],
            number=int(flat["num"]),
        )
    positional = _POSITIONAL_RE.match(text)
    if positional:
        return ParsedId(
            program=positional["prog"],
            sub_program=positional["sub"],
            module=positional["mod"],
            kind=positional["kind"],
            feature=None,
            number=int(positional["num"]),
        )
    raise IdParseError(f"not a valid Assured ID: {text!r}")


def format_id(parsed: ParsedId) -> str:
    if is_positional(parsed):
        return f"{parsed.program}.{parsed.sub_program}.{parsed.module}.{parsed.kind}-{parsed.number:03d}"
    return f"{parsed.kind}-{parsed.feature}-{parsed.number:03d}"


def is_positional(parsed: ParsedId) -> bool:
    return parsed.program is not None


@dataclass(frozen=True)
class IdRecord:
    """A single ID with its source artefact and forward links."""

    id: str
    kind: str
    source: str
    satisfies: List[str]


_HEADING_RE = re.compile(
    r"^###\s+(?P<id>(?:P\d+\.SP\d+\.M\d+\.)?(?:REQ|DES|TEST|CODE)-(?:[a-z0-9][a-z0-9-]*-)?\d+)\b"
)
_SATISFIES_RE = re.compile(r"^\*\*satisfies:\*\*\s+(?P<refs>.+)$", re.MULTILINE)
_REF_ID_RE = re.compile(
    r"\b((?:P\d+\.SP\d+\.M\d+\.)?(?:REQ|DES|TEST|CODE)-(?:[a-z0-9][a-z0-9-]*-)?\d+)\b"
)


def build_id_registry(project_root: Path) -> List[IdRecord]:
    """Walk docs/specs/ and collect every declared ID with its forward links."""
    specs_dir = project_root / "docs" / "specs"
    records: List[IdRecord] = []
    if not specs_dir.is_dir():
        return records
    for spec_file in sorted(specs_dir.glob("**/*.md")):
        text = spec_file.read_text(encoding="utf-8")
        rel_source = str(spec_file.relative_to(project_root))
        in_code_block = False
        current_id: Optional[str] = None
        current_satisfies: List[str] = []

        def _flush() -> None:
            nonlocal current_id, current_satisfies
            if current_id is not None:
                records.append(
                    IdRecord(
                        id=current_id,
                        kind=parse_id(current_id).kind,
                        source=rel_source,
                        satisfies=current_satisfies,
                    )
                )
            current_id = None
            current_satisfies = []

        for line in text.splitlines():
            if line.strip().startswith("```"):
                in_code_block = not in_code_block
                continue
            if in_code_block:
                continue
            heading = _HEADING_RE.match(line)
            if heading:
                _flush()
                current_id = heading["id"]
                continue
            satisfies = _SATISFIES_RE.match(line)
            if satisfies and current_id is not None:
                current_satisfies = _REF_ID_RE.findall(satisfies["refs"])
        _flush()
    return records


def render_id_registry(records: List[IdRecord]) -> str:
    """Render the registry as a markdown table."""
    lines = [
        "<!-- Generated by kb-rebuild-indexes; do not edit by hand. -->",
        "# ID Registry",
        "",
        "| ID | Kind | Source | Satisfies |",
        "|----|------|--------|-----------|",
    ]
    for r in records:
        sat = ", ".join(r.satisfies)
        lines.append(f"| {r.id} | {r.kind} | {r.source} | {sat} |")
    return "\n".join(lines) + "\n"
