# See https://pre-commit.com for more information
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: pretty-format-json
        args: ['--autofix', '--no-sort-keys']
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      # CRITICAL: Add Python syntax validation
      - id: check-ast
        name: Check Python AST (Syntax)
        description: 'Check whether Python files parse as valid python'
      - id: check-builtin-literals
        name: Check builtin type constructor use (Python)
      - id: debug-statements
        name: Debug statement (Python)

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.9

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ['--max-line-length=127', '--extend-ignore=E203,W503']

  # Temporarily disabled - requires comprehensive type annotation effort
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.8.0
  #   hooks:
  #     - id: mypy
  #       args: ['--config-file=mypy.ini']
  #       exclude: ^tools/framework-setup\.py$
  #       additional_dependencies: ['types-requests', 'types-PyYAML']
