---
name: AI-First SDLC Validation

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pre-commit

      - name: Validate Architecture Documents
        run: |
          echo "🏗️ Validating Architecture Documents..."
          python tools/validation/validate-architecture.py --strict

      - name: Check Technical Debt
        run: |
          echo "🔍 Checking for Technical Debt..."
          python tools/validation/check-technical-debt.py --threshold 0

      - name: Run validation pipeline
        run: |
          python tools/validation/validate-pipeline.py --ci \
            --checks branch proposal architecture technical-debt type-safety

      - name: Check feature proposal
        if: github.event_name == 'pull_request'
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          python tools/validation/check-feature-proposal.py --branch "$BRANCH_NAME"

      - name: Run pre-commit hooks
        run: pre-commit run --all-files
