---
name: AI-First SDLC Validation

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pre-commit

      - name: Run validation pipeline
        run: python tools/validate-pipeline.py --ci

      - name: Check feature proposal
        run: python tools/check-feature-proposal.py

      - name: Run pre-commit hooks
        run: pre-commit run --all-files
